import type { Metadata } from "next";
import { ContentPage } from "@/components/content-page";

export const metadata: Metadata = { title: "Our Story" };

export default function OurStoryPage() {
  return <ContentPage eyebrow="Tamanna Sharma · The founder’s story" title="It started with a simple search for something better." intro="A personal search became a larger purpose — to bring traditional sweetness out of the grey and into the light.">
    <h2>A familiar kind of sweetness</h2><p>My journey with Zucero began with a personal search. When I started my fitness journey, I began looking more closely at what I was consuming — and naturally, I started looking for an alternative to refined sugar.</p><p>Having grown up in the heart of Haryana, sweetness had always meant something very different to me. Jaggery after a meal was tradition. It was familiar. It was something I genuinely loved.</p>
    <h2>Why had we never questioned our sugar?</h2><p>As I began looking for it more consciously, I found that the story of “natural” did not always match my experience of the product. It made me realise how difficult it could be to choose with confidence.</p><p>Jaggery, Khand and Mishri are everywhere. I wanted to build a distinctive brand that made purity, provenance and traditional craft its identity. If we can be so conscious about what goes into our food, why have we never really questioned our sugar?</p>
    <h2>Sweetness will always be part of life</h2><p>Festivals, celebrations, desserts and little moments of indulgence will always be part of life. Perhaps the answer isn’t to take sweetness away. Perhaps it is to make a more thoughtful choice when we choose it.</p><p>That is where Zucero began: a personal search that became a larger purpose.</p>
    <h2>If marketing can create trust, it should also earn it.</h2><p>With leadership experience across India and international markets, Tamanna Sharma has spent years understanding the power of brands — and the power of trust. A good brand is not built by marketing alone. It is built by a good product, and strengthened by trust earned over time.</p><p>Marketing has the power to shape perceptions, influence choices and bring products into our homes. But that power comes with a responsibility. If marketing can make us notice what is in front of us, why not use it to bring attention to the good that often remains unseen?</p><p>Not by making bigger promises. Not by creating unnecessary noise. But by making people more aware of what they choose.</p><p>Zucero exists to make good more visible.</p><p className="note">Zucero products contain sugar. Traditional processing does not make them sugar-free or a treatment for health conditions.</p>
  </ContentPage>;
}
